### ISSUE TITLE
Use workshop to get md5sum of client-server container image

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#100]
Client-server container images are uniquely identified by their image tag, in that the tag is an md5sum of a combination of software requirements that were used to construct the image.  Currently, rickshaw-run generates this md5sum, based on a md5sum of all workshop-requirement and userenv files.  This is both too much input and not enough.  It's too much because there's a lot of info in these files which may have nothing to do with the current userenv (like a RPM for rhubi8, but you are building for userenv fedora33).  It's also not enough input, because these workshop requirement files alone may not have enough information in them to get a unique md5sum.  For example, having a "manual" requirement which compiles a git repo may have source files change over time.

For these reasons, we need to use workshop to get the md5sum for us.  Workshop will only use the actual requirements (requirements that apply to only the userenv requested), and eventually, workshop will support something better for source-built requirements (likely generating a md5sum on the source files).

**Comment by k-rister** [comment]
I already did a bunch of fixes towards improving this, most notably the first one:

https://github.com/perftool-incubator/rickshaw/commit/d5c88850d825ea42d35a807daf2b54e8cc5df68f

https://github.com/perftool-incubator/rickshaw/commit/c5e8b986134c9edcc5f87e1471a0b2e290ac9f2d

https://github.com/perftool-incubator/rickshaw/commit/c678e8a7256e1a7f3f6ca0ee14e36fbd03a3fde3
