### ISSUE TITLE
Move to a one tool per engine execution model

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/rickshaw#288]

**Comment by atheurer** [comment]
A brief approach to making this happen:
1) start with easiest endpoint (remotehost) and rework to launch a separate engine per tool.  Don't make any changes to how engines are built yet, just use the userenv that has everything.
2) repeat for osp and k8s endpoints
   2b) k8s: when an engine is created to be a benchmark client or server, need to explore multiple containers per pod, 1 for the client/server and others for tools [that need to run in the same namespace as the client/server].
3) Work on userenv building with just one benchmark or one tool
4) Start using the one-benchmark/tool userenvs
