### ISSUE TITLE
RFE - OSP Endpoint support for Guest VM kernel boot parameter and tuned profile

### ISSUE THREAD

**Issue by pradiptapks** [perftool-incubator/rickshaw#350]
For the `bench-trafficgen` test with osp endpoint, the guest VM needs to support with custom kernel boot param with CPU isolations and a hugepage. Also need to keep a tuned profile with selective CPU cores.

Command:

`crucible run trafficgen --mv-params mv-params-perf122-dpdk-pvp-testpmd.json --bench-ids trafficgen:1 --num-samples=1 --max-sample-failures=1 --tags Test:dpdk --test-order r --endpoint osp,host:192.168.24.1,user:stack,flavor:default:stream8,flavor:server-1:stream8,flavor:server-1:stream8,availability-zone:server-1:nova,cpu-partitioning:server-1,server:1,osruntime:podman,userenv:alma8,vm-image:stream8 --endpoint remotehost,host:perf122.perf.lab.eng.bos.redhat.com,user:root,client:1,userenv:alma8,cpu-partitioning:client-1,disable-tools:1`

Error logs of VM

```
# less run/iterations/iteration-1-fail/sample-1-fail-1/server/1/trafficgen-server-start-stderrout.txt
...trim...
per-node-hugepages:
/sys/devices/system/node/node0/hugepages/hugepages-1048576kB
free_hugepages:
0
nr_hugepages:
0
surplus_hugepages:
0
/sys/devices/system/node/node1/hugepages/hugepages-1048576kB
ls: cannot access '/sys/devices/system/node/node1/hugepages/hugepages-1048576kB': No such file or directory
These files exist in ./msgs/rx:
total 8
-rw-r--r--. 1 root root 69 Dec  8 09:29 infra-start-end:1
-rw-r--r--. 1 root root 38 Dec  8 09:29 infra-start-end:2
Resolving devices for testpmd based on devices [0000:00:04.0,0000:00:05.0]
Resolving device [0000:00:04.0]
Device [0000:00:04.0] did not match regex for environemnt variable [^VAR:(\w+)(:(.+)){0,1}] or devtype [^([virtio|vf]-\d+)$]
The device [0000:00:04.0] matched the regex for a PCI location ID
Resolving device [0000:00:05.0]
Device [0000:00:05.0] did not match regex for environemnt variable [^VAR:(\w+)(:(.+)){0,1}] or devtype [^([virtio|vf]-\d+)$]
The device [0000:00:05.0] matched the regex for a PCI location ID
Device 1: 0000:00:04.0
Device 1 NUMA node: -1
Device 2: 0000:00:05.0
Device 2 NUMA node: -1
There are no housekeeping CPUs to use for testpmd

```

**Comment by k-rister** [comment]
This requires the VM image to be properly configured rather than relying on the endpoint.
