### ISSUE TITLE
Implement multi-bench example B

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#391]
This may not involve coding changes, we'll see, but rickshaw seemed like the most appropriate place to associate with this work.

Multi-bench example B consists of running a trafficgen test, with 1 or more forwarders, while running 1 or more iperf UDP tests.  For this first pass, this does *not* use binary search, only one-shot tests, since binary-search tests have an indeterministic run-time.

This test will likely be used in the following way:
- Tester establishes peak packet rate for N forwarders using regular trafficgen binary search test
- Tester combines trafficgen with iperf.
  - trafficgen uses one-shot with peak rate found from previous binary-search test.
  - tester adds M pairs of client/servers on the same host to run iperf, in increasing amounts of traffic, to see the effect on the trafficgen results.

**Comment by k-rister** [comment]
Not really appropriate for Crucible development work.
