### ISSUE TITLE
Implement generic message passing between client and server benchmark scripts

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#53]
Make use of the feature in roadblock to send and receive messages between clients and servers, and allow the benchmark scripts that are executed by the clients and servers to read received messages and queue messages to send.

There will be a message queue for Rx and Tx for every client and server, for every benchmark-iteration-sample.  All messages received from roadblock syncs having to do with executing a benchmark-iteration-sample are accumulated in that iteration-samples Rx dir.  When a benchmark script wants to send a message, it simply creates a file in the directory representing the Tx queue, and on the next roadblock sync, all messages from the Tx queue are loaded into 1 messages-json for roadblock, removed from the Tx queue and the messages sent on that roadblock sync.

Any time a benchmark script wants to create a message, it must adhere to a single message int he roadblock format: https://github.com/perftool-incubator/roadblock/blob/master/roadblock.py#L198

**Comment by atheurer** [comment]
This will be the building block for issue https://github.com/perftool-incubator/rickshaw/issues/20

**Comment by k-rister** [comment]
> Any time a benchmark script wants to create a message, it must adhere to a single message int he roadblock format: https://github.com/perftool-incubator/roadblock/blob/master/roadblock.py#L198

I think you mean this link: [https://github.com/perftool-incubator/roadblock/blob/master/roadblock.py#L130](https://github.com/perftool-incubator/roadblock/blob/master/roadblock.py#L130)

**Comment by atheurer** [comment]
Yes, that's the one.

This is complete with PR https://github.com/perftool-incubator/rickshaw/pull/54

Note that benchmarks do not need to use the "full" schema that roadblock uses.  It only needs to provide a valid json object.  The rest of the JSON roadblock uses is added by client-server-script.  This simplifies the usage and should not require any sort of validator for the object (other than ensuring the object is valid JSON).
