### ISSUE TITLE
Add tool execution infrastructure to rickshaw and the local endpoint

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#7]
Also create a tool-syststat project and use mpstat [initially] for a default tool

**Comment by k-rister** [comment]
> Also create a tool-syststat project and use mpstat [initially] for a default tool

Should we target the creation of one container image for sysstat but then launch N containers depending on the tools we plan on using (mpstat, sar, iostat, etc.).  Or someone try to run them in the same container?

**Comment by atheurer** [comment]
I think I will try running in the same container.  They all need the same package anyway.  Additionally, I think I will just organize the tool project as "sysstat".  So, from a user perspective, you will ask for sysstat, and you will specify what from sysstat you want.  This way we only have one git repo for all of the sysstat tools.

**Comment by k-rister** [comment]
I think that idea, something like "enable sysstat with modules X, Y, & Z"

**Comment by atheurer** [comment]
We would use the same approach for "proc-stat" tool, a tool which captures from 1 to dozens of files in proc (ones that are not adequately captured by other tools) like /proc/interrupts, etc

**Comment by k-rister** [comment]
I think we will have to come up with some kind of parent process that manages the children since the container will need a single entry point.

**Comment by atheurer** [comment]
Most of this is working with https://github.com/perftool-incubator/rickshaw/pull/8
Post-processing is not done yet

**Comment by atheurer** [comment]
Next step will be to add a post-process script for sysstat (mpstat) and then add code to rickshaw to call the tool-specific post-process scripts, then update rickshaw-post-process to include consolidating any tool post-processed data into rickshaw-result.json

**Comment by atheurer** [comment]
Since basic tool execution works including "collectors" for k8s endpoint, I am going to close this issue and save post-processing for another issue
