### ISSUE TITLE
Don't start tool pods for masters if masters are not detected

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#71]
Should seem pretty obvious, but k8s is trying to start pods for an empty list of masters and fails.  Don't do this.

**Comment by k-rister** [comment]
Why is the masters list empty?

**Comment by atheurer** [comment]
See https://github.com/perftool-incubator/rickshaw/issues/70

**Comment by atheurer** [comment]
Fixed with PR #72
