### ISSUE TITLE
rickshaw-export needs to parse ES index responses for errors

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#80]
We need to know if any of the indexing for a run has failed.  It is possible that some, but not all documents have failed.  For example, a particular metric might have failed because it is using an invalid field in metric_desc.

Some of this could be caught earlier by ensuring we have matching schemas between CDM and rickshaw.  We just need to ensure the ES template agrees with a corresponding JSON schema, like metric_desc.base (from CDM) agrees with bench-metric.json (from rickshaw, using json-schema.org validator).  At the moment these are very close, but there are some difference, like bench-metric.json does not restrict the field names for metric_desc{}.

**Comment by k-rister** [comment]
Could this be a use for [json-validator](https://github.com/perftool-incubator/junk-drawer/blob/master/bin/json-validator)?  Or am I missing the point?

**Comment by atheurer** [comment]
Yes, we do need to use json validator before submitting a request to index a document, but we need json-validator schema that matches the ES template.  Ideally it would be great if we had a script which could read the ES template format and create the JSON schema, but in absence of that, we can just manually create the template, and make sure we update it when we update the ES template.  After all of this, IMO we should still be tracking the return code from the index operation and flag this when it fails.

**Comment by atheurer** [comment]
fixed with https://github.com/perftool-incubator/rickshaw/pull/159
