### ISSUE TITLE
Rickshaw and its endpoints to push/pull from a user-defined container-registry-location

### ISSUE THREAD

**Issue by atheurer** [perftool-incubator/rickshaw#9]
Rickshaw currently uses workshop to request a container image build.  These images are, however, only available on the local host and therefore only the 'local' endpoint can use them via 'buildah' commands.  After images are built via workshop, rickshaw needs to put these images into a registry where these images are available over a network.  These images are not static, and can be different from one run of rickshaw to the next.  Using only a specific registry (like quay.io or docker.io) is not a solution that will work for everyone because of possible access restrictions or network bandwidth issues.

**Comment by atheurer** [comment]
@k-rister do you think rickshaw should be responsible for taking buildah images from workshop and managing a user-defined registry, or should this be handled entirely within workshop itself (and rickshaw just tells it the requirements and the registry location to use)?

**Comment by k-rister** [comment]
@atheurer Hmm, I'm not real sure about which project to do it in but I am pretty sure I don't want to do it in workshop.pl itself.  I would like to leave that as strictly a image building tool but that doesn't mean there couldn't be some supporting scripts that handle the stuff you are referring to bundled along with it.

One thing I do think is an interesting ask is whether or not this is the kind of thing that crucible is supposed to be doing in terms of gluing these different pieces together?  Or are we just going to have situations where we have really tight linkage between some of the subprojects?

**Comment by atheurer** [comment]
I am fine with not having workshop deal with it directly, but I do want it handled in a single place so we don't end up duplicating the effort.

I am not sure if I want any core or essential code in crucible.  I view crucible as cobbling together projects and hiding the details from the user, but not being responsible for implementing any core function [other than the user CLI].

I am leaning towards rickshaw handling the registry management simply because it is the only project which relies on where those images need to be.  I just needed to be sure that was fine with you.  I already have a separate bash script which takes the buildah image and pushes it to quay.  I might incorporate that into the rickshaw-run script or write a new one, not sure.  Regardless where it goes, this is the #1 thing to implement before anyone else can (without significant help) run a crucible test on their own.  Actually we could also use the actual crucible interface to do this, but with some guidance a user can run the rickshaw command themselves.  That will be the second thing I work on.

**Comment by k-rister** [comment]
What are your thoughts on how/if to use [parking-garage](https://github.com/perftool-incubator/parking-garage)?  The big issue I see is the insecure registry behavior of something like OCP.  I wonder if I did into it more if I could someone force it to have real/valid SSL certs and drop the insecure nature.

**Comment by atheurer** [comment]
How does OCP change with the registry being insecure?  FWIW I was going to start the mgmt of the registry by using quay simply because I know it works now.  I am hoping whatever configuration needs to be done to "add" a registry to a cluster is the same whether it is k8s or ocp.  In the first phase I will skip the step to add the registry since I know ocp works with quay out of the box.  Once basic functionality works with quay, I would then add the ability to use any registry.

**Comment by k-rister** [comment]
As I currently understand it, the steps that are required to get OCP to use an insecure registry is what causes the entire cluster to do a rolling reboot.  If the registry were secure (ie. had valid SSL certs) then this would not happen (I think).

**Comment by k-rister** [comment]
FWIW, the insecure registry stuff is easily handled by just a few CLI args with `buildah` and/or `podman`.

**Comment by atheurer** [comment]
I think we can mark this as done and enhance as needed later.  We support pushing to any user-defined registry, and it seems to work well with quay.io.
